import Link from "next/link";
import { ArrowRight, CheckCircle, Clock, FileText, Globe, Scale, ShieldCheck } from "lucide-react";

const features = [
  { icon: <FileText size={22} />, title: "Digital Applications", desc: "Submit and track your instrument verification applications entirely online - no paper, no queues." },
  { icon: <Clock size={22} />, title: "Real-Time Tracking", desc: "Follow your application through every stage: review, inspection, testing, and certification." },
  { icon: <ShieldCheck size={22} />, title: "Tamper-Proof Certificates", desc: "QR-enabled digital certificates with instant public verification to prevent counterfeiting." },
  { icon: <Globe size={22} />, title: "Nationwide Coverage", desc: "Connect with Legal Metrology Officers and approved test centres across all states." },
];

const workflow = [
  ["01", "Apply Online", "Submit your instrument details and required documents through the secure portal."],
  ["02", "LMO Review", "A Legal Metrology Officer reviews your application and schedules an inspection."],
  ["03", "Inspection & Testing", "On-site inspection and laboratory testing at a GATC facility if required."],
  ["04", "Certificate Issued", "Receive your digital verification certificate with unique QR code for public verification."],
];

export default function LandingView() {
  return <div className="min-h-screen bg-slate-50 font-body">
    <nav className="fixed top-0 inset-x-0 z-50 bg-white border-b border-slate-200"><div className="max-w-7xl mx-auto px-4 sm:px-6 flex items-center justify-between h-16"><Link href="/" className="flex items-center gap-2.5"><div className="w-8 h-8 rounded-lg bg-gradient-royal flex items-center justify-center"><Scale size={16} className="text-white" /></div><span className="font-bold text-lg font-display" style={{ color: "#0d1b3e" }}>UMVP</span><span className="hidden sm:block text-slate-400 text-sm ml-1">Unified Metrology Verification Portal</span></Link><div className="flex items-center gap-3"><Link href="/verify/demo" className="text-sm text-slate-600 hover:text-slate-900">Verify Certificate</Link><Link href="/login" className="text-sm font-medium text-slate-700 hover:text-slate-900">Sign In</Link><Link href="/register" className="bg-gradient-royal text-white text-sm font-semibold px-4 py-2 rounded-lg hover:opacity-90">Get Started</Link></div></div></nav>
    <section className="relative pt-24 pb-20 overflow-hidden" style={{ background: "linear-gradient(135deg, #0d1b3e 0%, #1a2d6b 60%, #0d9488 100%)" }}><div className="absolute inset-0 opacity-10" style={{ backgroundImage: "radial-gradient(circle at 20% 50%, #2563eb 0%, transparent 50%), radial-gradient(circle at 80% 20%, #14b8a6 0%, transparent 40%)" }} /><div className="relative max-w-7xl mx-auto px-4 sm:px-6"><div className="max-w-3xl"><div className="inline-flex items-center gap-2 bg-white/10 border border-white/20 rounded-full px-4 py-1.5 mb-6"><span className="w-1.5 h-1.5 bg-teal-400 rounded-full" /><span className="text-white/80 text-xs font-medium">Government of India · Legal Metrology</span></div><h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold text-white font-display leading-tight mb-6">Instrument Verification, <span className="text-transparent bg-clip-text" style={{ backgroundImage: "linear-gradient(135deg, #2dd4bf, #3b82f6)" }}>Simplified</span></h1><p className="text-lg text-white/70 mb-8 max-w-xl">The national digital platform for legal metrology instrument verification. Submit applications, track progress, and receive tamper-proof certificates - all online.</p><div className="flex flex-wrap items-center gap-3"><Link href="/login" className="flex items-center gap-2 bg-white font-semibold px-6 py-3 rounded-xl hover:bg-blue-50" style={{ color: "#0d1b3e" }}>Open Workspace <ArrowRight size={16} /></Link><Link href="/verify/demo" className="flex items-center gap-2 border border-white/30 text-white font-medium px-6 py-3 rounded-xl hover:bg-white/10"><ShieldCheck size={16} /> Verify a Certificate</Link></div></div></div><div className="relative max-w-7xl mx-auto px-4 sm:px-6 mt-14"><div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{[["1,200+", "Registered Users"], ["3,800+", "Applications Processed"], ["47", "Active LMO Officers"], ["2,700+", "Certificates Issued"]].map(([value, label]) => <div key={label} className="bg-white/15 border border-white/25 rounded-xl px-5 py-4 text-center"><div className="text-2xl font-bold text-white font-display">{value}</div><div className="text-white/70 text-xs mt-1">{label}</div></div>)}</div></div></section>
    <section className="py-20 max-w-7xl mx-auto px-4 sm:px-6"><div className="text-center mb-12"><h2 className="text-3xl font-bold text-slate-800 font-display mb-3">Built for Legal Metrology</h2><p className="text-slate-500 max-w-md mx-auto">A purpose-built platform for instrument owners, government officers, and accredited test centres.</p></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">{features.map((feature) => <article key={feature.title} className="bg-white rounded-2xl border border-slate-200 p-6 hover:shadow-lg transition-shadow"><div className="w-11 h-11 rounded-xl bg-blue-50 text-blue-600 flex items-center justify-center mb-4">{feature.icon}</div><h3 className="font-bold text-slate-800 font-display mb-2">{feature.title}</h3><p className="text-slate-500 text-sm leading-relaxed">{feature.desc}</p></article>)}</div></section>
    <section className="py-20 bg-white"><div className="max-w-7xl mx-auto px-4 sm:px-6"><div className="text-center mb-12"><h2 className="text-3xl font-bold text-slate-800 font-display mb-3">How It Works</h2><p className="text-slate-500">From application to certified instrument in four steps.</p></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-8">{workflow.map(([step, label, desc]) => <article key={step} className="relative flex flex-col items-center text-center"><div className="w-12 h-12 rounded-full bg-gradient-royal text-white font-bold font-mono flex items-center justify-center mb-4 text-sm shadow-lg">{step}</div><h3 className="font-bold text-slate-800 font-display mb-2">{label}</h3><p className="text-slate-500 text-sm leading-relaxed">{desc}</p></article>)}</div></div></section>
    <section className="py-20" style={{ background: "linear-gradient(135deg, #f8fafc, #eff6ff)" }}><div className="max-w-7xl mx-auto px-4 sm:px-6"><div className="text-center mb-12"><h2 className="text-3xl font-bold text-slate-800 font-display mb-3">Who Uses UMVP?</h2></div><div className="grid md:grid-cols-3 gap-6">{[["⚖️", "Instrument Users", "Business owners, traders, and industries with measuring instruments."], ["🏛️", "Legal Metrology Officers", "Government-appointed officers who review applications and conduct inspections."], ["🔬", "Approved Test Centres", "Government-approved laboratories conducting technical testing and calibration."]].map(([icon, role, desc]) => <article key={role} className="bg-white rounded-2xl border border-slate-200 p-6 shadow-sm"><div className="text-3xl mb-4">{icon}</div><h3 className="font-bold text-slate-800 font-display text-lg mb-2">{role}</h3><p className="text-slate-500 text-sm leading-relaxed">{desc}</p><Link href="/register" className="inline-flex items-center gap-1.5 mt-4 text-blue-600 text-sm font-medium">Register now <ArrowRight size={14} /></Link></article>)}</div></div></section>
    <section className="py-16" style={{ background: "linear-gradient(135deg, #0d1b3e, #1a2d6b)" }}><div className="max-w-3xl mx-auto px-4 sm:px-6 text-center"><h2 className="text-3xl font-bold text-white font-display mb-4">Ready to verify your instruments?</h2><p className="text-white/60 mb-8">Join businesses who have digitized their metrology compliance with UMVP.</p><Link href="/login" className="inline-flex items-center gap-2 bg-white font-semibold px-6 py-3 rounded-xl" style={{ color: "#0d1b3e" }}>Open workspace <ArrowRight size={16} /></Link></div></section>
    <footer className="bg-slate-900 text-slate-400 py-8"><div className="max-w-7xl mx-auto px-4 sm:px-6 flex flex-col sm:flex-row items-center justify-between gap-4"><div className="flex items-center gap-2"><Scale size={16} /><span className="font-semibold text-white text-sm">UMVP</span><span className="text-slate-600 text-xs">· Ministry of Consumer Affairs</span></div><div className="flex items-center gap-2 text-xs"><CheckCircle size={12} className="text-green-500" /><span>Government digital portal</span></div></div></footer>
  </div>;
}